name: CultureMatters
favicon: null
layout_spectrum: 0.58749
typography_spectrum: 0.75523
title: Culture Matters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0a5a7a'
    - '#5f8c9b'
    - '#a6b2ae'
    - '#91160b'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
