name: CultureMatters
favicon: null
layout_spectrum: 0.24282
typography_spectrum: 0.75523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a5a5a'
    - '#095a5a'
    - '#ffffff'
    - '#9b9b9b'
    - '#e0e0e0'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
